歌詞と時間情報のAPI実装
cyder-akashi/Aktiva-V2-Server pull request #24
Opened 2017-08-05 12:58 UTC by crome110

close #10

2017-08-05 14:48 UTC, chigichan24 commented on db/seeds.rb
> +song_num = 5
db:seedしてもアクセス出来ないけどどうなってんの？

2017-08-05 14:56 UTC, Mori-Atsushi commented on db/seeds.rb
> +song_num = 5
seedしても追加されるだけなので、注意
一旦DB削除してからもう一度seedするのがおすすめ
```sh
bundle exec rake db:migrate:reset
bundle exec rake db:seed
```

2017-08-05 16:18 UTC, chigichan24 commented on db/seeds.rb
> +song_num = 5
http://0.0.0.0:3000/api/v1/lyrics?songId=1 ですよね？

2017-08-05 23:25 UTC, Mori-Atsushi commented on db/seeds.rb
> +song_num = 5
ごめん、こっちだ
http://0.0.0.0:3000/api/v1/lyrics?song_id=1

2017-08-06 01:24 UTC, chigichan24 commented on db/seeds.rb
> +song_num = 5
ごめん．というか普通にコードよめばわかったわ．昨日死ぬほど疲れてたから(いいわけ

2017-08-06 01:40 UTC, chigichan24 commented
song_infoと大きく変わってないから冗長感あるけど，まあプロトタイプだしいいかな．ちなみに動作(コード)の説明とかできる？ @crome110  くん．軽くでいいから理解レベルを知りたいので書いたコードをふんわり説明してほしい．それが終わったらapproveだしてあげる♥

2017-08-06 04:25 UTC, Mori-Atsushi commented
> song_infoと大きく変わってないから冗長感ある

そこは微妙に気になった。
コントローラは同じにしといたほうが良かったのかな？

2017-08-06 04:34 UTC, Mori-Atsushi commented
意地悪で笑った

2017-08-06 04:57 UTC, mori-atsushi requested changes

2017-08-06 04:57 UTC, Mori-Atsushi commented on app/views/api/v1/lyrics/index.json.jbuilder
> +  json.array!(@song.lyrics) do |lyric|
歌詞がtime順に並んでいる保証がないので、修正お願いできますか？

2017-09-14 02:35 UTC, Mori-Atsushi commented
このPR僕が引き継ぎますね

2017-09-14 03:25 UTC, mori-atsushi reviewed
このレビューも @euglena1215 にお願いします！

2017-09-14 03:25 UTC, mori-atsushi submitted a review, later dismissed

2017-09-14 18:28 UTC, euglena1215 requested changes

2017-09-14 18:28 UTC, euglena1215 commented on app/controllers/api/v1/lyrics_controller.rb
> +        render 'index', formats: 'json', handlers: 'jbuilder'
indexメソッドでrenderを呼んでいるので 'index' は省略できそうな気がします。
(確信はないのでできなかったらごめんなさい)

これは完全に機能要件の話にはなってくるんだけど、
```
respond_to do |format|
  format.json { render formats: 'json', handlers: 'jbuilder' }
  format.any { render text: "Not Acceptable", status: :not_acceptable }
end
```
みたいな形で.json以外のアクセスは弾く、とかは必要ない？

2017-09-14 18:33 UTC, euglena1215 requested changes

2017-09-14 18:33 UTC, euglena1215 commented on app/controllers/api/v1/lyrics_controller.rb
> +        @lyrics = @song.lyrics.order(:time)
API叩いたらtimeで毎回ORDER BYするのが確定してるならtimeにindex付けときたくない？

2017-09-15 06:01 UTC, Mori-Atsushi commented
修正しました。

2017-09-16 16:48 UTC, euglena1215 commented on app/controllers/api/v1/lyrics_controller.rb
> +        render 'index', formats: 'json', handlers: 'jbuilder'
@Mori-Atsushi 
これは'index'が省略できなくて、他のformatからのアクセスを弾くとかは必要ないからスルーした、という認識でおーけー？

2017-09-16 23:10 UTC, Mori-Atsushi commented on app/controllers/api/v1/lyrics_controller.rb
> +        render 'index', formats: 'json', handlers: 'jbuilder'
このコメントを見てなかったというわけです

2017-09-17 13:14 UTC, Mori-Atsushi commented
indexは省略しました。

respond_toは言われたとおり書いたら .json とフォーマットを明記しないとアクセスできなくなった。
あと、apiは全部jsonなら、routesで指定するのがいいかも？
http://mgi.hatenablog.com/entry/2015/10/17/232239

あと、別のAPIも同様なので別Issueで議論すべきだと思いました。

2017-09-19 06:09 UTC, euglena1215 commented
確かにそれはそうですね、
routingの変更は別issueってことでこのPRはマージしちゃいます

2017-09-19 06:10 UTC, euglena1215 approved these changes

2017-09-19 06:10 UTC, merged