キーワード検索APIに検索ヒット件数を追加
cyder-akashi/Aktiva-V2-Server pull request #33
Opened 2017-08-23 14:00 UTC by Mori-Atsushi

close #32

SQLが2度実行されて無駄感があるんだけどどうなんだろう？

2017-09-06 13:50 UTC, chigichan24 requested changes

2017-09-06 13:50 UTC, chigichan24 commented on app/models/search/song.rb
> +    def hit_num
```
hit_num
```
は直感的になにが入ってるかわからないかな．

2017-09-06 13:50 UTC, chigichan24 commented on app/models/search/song.rb
> +      @songs = ::Song.where(contains(:title, keyword))
一度
```
@songs 
```
にいれたほうが良いとか，なんか根拠とかある？

2017-09-06 13:52 UTC, Mori-Atsushi commented on app/models/search/song.rb
> +      @songs = ::Song.where(contains(:title, keyword))
where文を2度書く必要はないなと思った次第であります。

2017-09-06 13:53 UTC, Mori-Atsushi commented on app/models/search/song.rb
> +    def hit_num
変数名の命名の話かな？
`hit_count` とかにすべき？

2017-09-06 14:13 UTC, chigichan24 commented on app/models/search/song.rb
> +    def hit_num
はい

2017-09-06 14:13 UTC, chigichan24 commented on app/models/search/song.rb
> +      @songs = ::Song.where(contains(:title, keyword))
@songsって複数箇所で使ってるっけ？スコープがまだちいさいところでも良い気がしたんだけど．

2017-09-06 14:18 UTC, Mori-Atsushi commented on app/models/search/song.rb
> +      @songs = ::Song.where(contains(:title, keyword))
ですね、修正します

2017-09-07 07:50 UTC, Mori-Atsushi commented
修正しました。
`@songs`は15行目と19行目で使ってたので、代わりに他メソッドで使用されてなかった`@keyword`を消したんだが、これでよかったかな？

2017-09-10 15:39 UTC, chigichan24 submitted a review, later dismissed

2017-09-10 15:41 UTC, euglena1215 commented on app/models/search/song.rb
> +      @songs.count
ActiveRecordで `count` はCOUNT(*)のクエリが発行されます。
単純に要素数が知りたいだけなら `length` を使いましょう。
その辺りを考えたくないなら `size` を使いましょう。

https://stackoverflow.com/questions/6083219/activerecord-size-vs-count

2017-09-10 15:53 UTC, euglena1215 commented on app/models/search/song.rb
>        offset_num = num * (page - 1)
numやpageはインスタンス変数になってないけどこれで値を取得できるんだっけ？

2017-09-14 02:28 UTC, Mori-Atsushi commented
修正しました。
@euglena1215 再レビューお願いします！

2017-09-14 18:35 UTC, euglena1215 approved these changes

2017-09-14 18:35 UTC, euglena1215 commented
LGTM

2017-09-15 02:09 UTC, Mori-Atsushi commented
@euglena1215 レビュー感謝！問題なければマージお願いします！
レビューワーがマージする事になっております。

2017-09-15 02:13 UTC, euglena1215 commented
@Mori-Atsushi 
![2017-09-15 11 12 26](https://user-images.githubusercontent.com/13253769/30463457-da0e9264-9a06-11e7-9634-8457df7cc655.png)

権限をください...!

2017-09-17 03:14 UTC, merged